# Generated by Django 5.1.4 on 2024-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
